Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,7 +15,7 @@ jobs:
             echo "Listing files complete."
       - attach_workspace:
           at: ~/workspace
-      - run: |
+      - run:
           SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
           echo "Sonar branch value is: $SONAR_BRANCH"
           echo "Sonar org value is: $SONAR_ORG"
@@ -25,8 +25,8 @@ jobs:
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.exclusions="**/android/**,**/ios/**" \
             -Dsonar.login="#SONAR_TOKEN" \
-            -Dsonar.branch.name="$CIRCLE_CIRCLE_BRANCH"  # Use CIRCLE_BRANCH here
-            -Dsonar.sources="."
+            -Dsonar.branch.name="$CIRCLE_BRANCH" \
+            -Dsonar.sources="." || (echo "Sonar Scanner failed. Check logs for details."; exit 1)
 
 workflows:
   build-and-test:
